var TimelineId = "timeline";
var TimelineId$ = "#" + TimelineId;
var CompositionId$ = "#composition";
var VSplitterId$ = "#VSplitter0";
var ViewportId$ = "#Viewport0";
var VScrollBarId$ = "#compositionHeight";
var TrackToolId$ = "#TrackTool0";
var TitleBarId$ = "#titleBar";
var BottomBarId$ = "#BottomBar0";
